apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - professor
  - student

patches:
  - target:
      group: batch
      kind: CronJob
      name: greet-cronjob
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "* * * * *"
