apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/hello

configMapGenerator:
  - name: hello-config
    behavior: merge
    envs:
      - .env

patches:
  - target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: hello-cronjob
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/command
        value:
          - /bin/sh
          - -c
          - |
            echo "hello dev, hello ${NAME}, you are ${POSITION}"
  - target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: hello-cronjob
    patch: |-
      - op: replace
        path: /spec/suspend
        value: true
nameSuffix: "-professor"

