apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - professor_hello
  - student_hello

patches:
  - target:
      group: batch
      kind: CronJob
      name: hello-cronjob
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "* * * * *"